### PR TITLE
gradle script to build and publish

### PR DESCRIPTION
**Pull request by lbergelson**
@tedsharpe Here's a whole blob of boilerplate to build and upload.  I think it's actually longer than the fermilite code :(  

 I taught the gradle script to build the C code as well, so you can do it all in a few commands.

To build and install a snapshot locally with only one of the shared libraries, just `./gradlew install printVersion`

To do a real upload 
```
scripts/build_both_dylib_and_so.sh
./gradlew uploadArchives printVersion -Drelease=true
```

The you just follow the sonatype process.

I uploaded 1.0.0-rc1-SNAPSHOT to our artifactory if you want to test your gatk-build against that.  When that is OK then we can do a proper release on central.

### CODE REVIEW

**Comment by lbergelson** [comment]
@tedsharpe Give this a shot and make sure it's working for you and I haven't missed anything essential in the transition from makefile -> gradle.  I can always drop the c build in gradle and just invoke the make file directly, but I wanted to see how doable it was and it seems like it's pretty reasonable in gradle.

**Comment by lbergelson** [comment]
On further thought, I'm probably missing some important bits in the fermilite build process that I haven't replicated.  Should probably just drop back to using the make files..

**Comment by lbergelson** [comment]
@tedsharpe Updated this to use the makefile directly.

**Comment by tedsharpe** [comment]
I'm fine with this, if you think it's ready to merge, @lbergelson.
I have a couple of small changes to make after you merge.  (I'll make a new PR.)

**Pull request merged**
